# -*- coding: utf-8 -*-
"""Processing image data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yu-nBgxdsxsjqEI2gZyTNML8yCGxnbKA

Image Data Processing
"""

# Getting the image with the help of web get
!wget 'https://img.freepik.com/premium-photo/cat-with-open-mouth-with-blur-background_802140-13680.jpg'

"""Libraries that can be used for image processing:
1. matplotlib.image
2. Pillow
3. OpenCV (cv2)
"""

#importing the image module from matplotlib library
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

# loading an image through matplotlib.image module
img = mpimg.imread('/content/cat.jpg')

type(img)

# for gettiing dimension
print(img.shape)

"""here (351, 626) represents the dimension and 3 represents the colour channel"""

print(img) # image getting converted into numy array

# converting numpy array into image
img_plot = plt.imshow(img)
plt.show()

"""Resizing the image using pillow library"""

from PIL import Image

img = Image.open('/content/cat.jpg')
img_resized = img.resize((200,200))

img_resized.save('/content/cat_resized.jpg')

#display the iimaghe from numpy array
img_res = mpimg.imread('/content/cat_resized.jpg')
img_res_plot = plt.imshow(img_res)
plt.show()

#shape of the image
print(img_res.shape)

"""Convert RGB images to Grayscale images using OpenCV"""

#importing OpenCV Library
import cv2

img = cv2.imread('/content/cat.jpg')

type(img)

img.shape

grayscale_image = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

type(grayscale_image)

grayscale_image.shape

"""cv2.imshow() will display the image but this will not be allowed in google collab.

for displaying the image in google colab we use -

**from google.colab.patches import cv2_imshow**
"""

from google.colab.patches import cv2_imshow

#display the image
cv2_imshow(grayscale_image)

# saving the garyscale image
cv2.imwrite('/content/cat_grayscale.jpg', grayscale_image) # here 'cv2' is a library , 'imwrite' is a function , 'cat_grayscale' is the name of image , 'graysacle' what type of image we are saving

